version: '3.7'
services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - '27017:27017'
    networks:
      - space
  redis:
    container_name: 'redis'
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - space
  space_api:
    image: node:16-alpine
    volumes:
      - ../:/space_api
    working_dir: /space_api
    ports:
      - 3333:3333
    env_file: ../.env
    environment:
      - APPLICATION_NAME=space_api
      - PORT=3333
      - MONGO_URI=mongodb://172.17.0.1:27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=123
      - MONGO_DB_NAME=launches
    command: ash -c "npm install && npm run dev"
    networks:
      - space
networks:
  space:
    driver: bridge
